steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/cicd-336010/pythondocker:latest", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/cicd-336010/pythondocker:latest"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment/deployment.yaml
      - --image=gcr.io/cicd-336010/pythondocker:latest
      - --location=us-central1-a
      - --cluster=test-cluster
